source 'https://github.com/CocoaPods/Specs'

project 'AFNetworking Tests'
workspace '../AFNetworking'
inhibit_all_warnings!

target 'iOS Tests' do
  platform :ios, '9.0'

  pod 'OCMock', '~> 2.1.1'
  pod 'Expecta', '~> 0.2.1'
  pod 'AFNetworking', :path => '../'
end

target 'OS X Tests' do
  platform :osx, '10.9'

  pod 'OCMock', '~> 2.1.1'
  pod 'Expecta', '~> 0.2.1'
  pod 'AFNetworking', :path => '../'
end